CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    balance INTEGER DEFAULT 80_000,
    last_reset TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tokens (
    token TEXT NOT NULL,
    expiration_date TIMESTAMP NOT NULL,
    user_id VARCHAR(255) REFERENCES users(id) ON DELETE CASCADE
);
