CREATE TABLE IF NOT EXISTS tokens (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    token TEXT NOT NULL,
    balance INTEGER DEFAULT 80000,
    last_reset TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

